---
- hosts: all
  sudo: true
  tasks:
    - name: Install java 8 preresequesits
      apt: name=python-software-properties

    - name: Add Java 8 repository
      apt_repository: repo='ppa:webupd8team/java'

    - name: Agree to oracle license
      debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true

    - name: Install Java 8
      apt: name=oracle-java8-installer force=yes
    - name: Remove "jenkins" package
      apt:
        name: jenkins
        force: yes
        state: absent
    - name: add jenkins repository key
      apt_key:
        url: "https://pkg.jenkins.io/debian-stable/jenkins.io.key"
        state: present
    - name: add jenkins repository
      apt_repository:
        repo: "deb https://pkg.jenkis.io/debian-stable binary/"
        state: present
    - name: install jenkins
      package:
        name=jenkins update_cache=yes state=latest
