---
- hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Installing necessary packets
      apt: name=jenkins update_cache=yes state=present
      with_items:
        - nginx
        - openjdk-7-jdk

    - name: Add Jenkins apt repository key.
      apt_key:
        url: https://jenkins-ci.org/debian/jenkins-ci.org.key
        state: present
        validate_certs: no

    - name: Add Jenkins apt repository.
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
        update_cache: yes

    - name: Installing Jenkins
      apt: name=jenkins update_cache=yes state=present
      with_items:
        - jenkins
