---
- name: Jenkins plugins play
  hosts: all
  vars:
    jenkins_plugins:
      build-pipeline-plugin:
        enabled: yes
      github:
        enabled: yes
      git:
        enabled: yes
    my_jenkins_params:
      url_username: admin
      url_password: "fake_password"
      url: http://localhost:8080
  tasks:
    - name: Start jenkins service
      become: true
      service:
        name: jenkins
        state: started
    - name: Install Jenkins Plugins
      become: true
      jenkins_plugin:
        name: "{{item.key}}"
        params: "{{ my_jenkins_params }}"
      with_dict: "{{jenkins_plugins}}"

  # pre_tasks:
  #    - name: show file context
  #      become: true
  #      command: cat /var/lib/jenkins/secrets/initialAdminPassword
  #      register: result
  #    - name: show file context
  #      become: true
  #      command: cat /var/lib/jenkins/secrets/initialAdminPassword
  #      register: result
